# 创建跨服地图画所需等级
cost: 20

# 跨服地图画lore
lore: "&7跨服地图画"

# 该隐藏地图画上的哪些图标
# 图标列表可在以下链接查询，使用*代表隐藏所有图标
hidden-cursors:
  # 玩家位置指针
  - WHITE_POINTER

# 是否禁用 1.x 插件数据转换器
# 如果你首次安装本插件时版本为 2.x，请保持这个选项开启
disable-outdate-converter: true
