# 创建跨服地图画所需等级
cost: 20

# 准备铁砧物品延时时间 (ticks)
# 如果设置为 auto，那么
# - 如果安装了 EcoEnchants，则延时 1 ticks 以免冲突
# - 如果是 Folia 服务端，则不延时，以免出现异步更新问题
anvil-delay-ticks: auto

# 当前服务器名字，用于区分不同服务器使用不同的地图ID。
# 如果设置为 server port，就使用当前子服端口作为服务器名字。
# 如果你的多个子服不在一台及其上，请务必设置此项！
server-name: server port

# 跨服地图画名称，支持 PAPI 变量（仅创建时替换变量，非动态更新变量）
# 仅在玩家未在铁砧更改物品名称时使用
name: "&7跨服地图画"
# 跨服地图画lore，支持 PAPI 变量，同上
lore:
  - "&7跨服地图画"

# 该隐藏地图画上的哪些图标
# 图标列表可在以下链接查询，使用*代表隐藏所有图标
# https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/map/MapCursor.Type.html
hidden-cursors:
  # 玩家位置指针
  - WHITE_POINTER

# 是否禁用 1.x 插件数据转换器
# 如果你首次安装本插件时版本为 2.x，请保持这个选项开启
disable-outdate-converter: true
